name: gn
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
jobs:
  get_started:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: download
        run: curl -o ${{github.workspace}}/gn.zip https://storage.googleapis.com/pigweed-docs-try/8773288279406328129/_static/gn.zip
      - name: unzip
        run: unzip ${{github.workspace}}/gn.zip -d ${{github.workspace}}/gn
      - name: build
        run: |
          cd ${{github.workspace}}/gn
          rm .gitmodules
          git submodule add https://pigweed.googlesource.com/pigweed/pigweed third_party/pigweed
          git submodule add https://pigweed.googlesource.com/third_party/github/nanopb/nanopb third_party/nanopb
          git submodule add https://pigweed.googlesource.com/third_party/github/FreeRTOS/FreeRTOS-Kernel third_party/freertos
          git submodule update --init --recursive
          source bootstrap.sh
          pw package install pico_sdk
          gn gen out
          ninja -C out
